### ISSUE TITLE
Warp Null

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Likes#37]
### Expected behavior

Should work

### Observed/Actual behavior

```
[00:07:45 INFO]: Over_Brave issued server command: /is likes top
[00:07:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is likes top' in world.bentobox.bskyblock.BSkyBlock$1(island)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:182) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2390) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2182) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'world.bentobox.warps.WarpSignsManager world.bentobox.warps.Warp.getWarpSignsManager()'
        at world.bentobox.likes.panels.user.TopLikesPanel.lambda$createPlayerButton$5(TopLikesPanel.java:283) ~[Likes-2.2.0.jar:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
        at world.bentobox.likes.panels.user.TopLikesPanel.createPlayerButton(TopLikesPanel.java:276) ~[Likes-2.2.0.jar:?]
        at world.bentobox.bentobox.api.panels.TemplatedPanel.makeAddonButton(TemplatedPanel.java:429) ~[BentoBox-1.20.1.jar:?]
        at world.bentobox.bentobox.api.panels.TemplatedPanel.makeButton(TemplatedPanel.java:373) ~[BentoBox-1.20.1.jar:?]
        at world.bentobox.bentobox.api.panels.TemplatedPanel.populateInventoryPanel(TemplatedPanel.java:116) ~[BentoBox-1.20.1.jar:?]
        at world.bentobox.bentobox.api.panels.TemplatedPanel.generatePanel(TemplatedPanel.java:69) ~[BentoBox-1.20.1.jar:?]
        at world.bentobox.bentobox.api.panels.TemplatedPanel.<init>(TemplatedPanel.java:57) ~[BentoBox-1.20.1.jar:?]
        at world.bentobox.bentobox.api.panels.builders.TemplatedPanelBuilder.build(TemplatedPanelBuilder.java:146) ~[BentoBox-1.20.1.jar:?]
        at world.bentobox.likes.panels.user.TopLikesPanel.build(TopLikesPanel.java:100) ~[Likes-2.2.0.jar:?]
        at world.bentobox.likes.panels.user.TopLikesPanel.openPanel(TopLikesPanel.java:669) ~[Likes-2.2.0.jar:?]
        at world.bentobox.likes.commands.user.PlayerTopCommand.execute(PlayerTopCommand.java:122) ~[Likes-2.2.0.jar:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:273) ~[BentoBox-1.20.1.jar:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:246) ~[BentoBox-1.20.1.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 20 more
```

### Steps/models to reproduce

Just updated Likes from 2.1.1 to 2.2

### BentoBox version

![image](https://user-images.githubusercontent.com/47111280/173254060-b84f515b-0785-49ab-b666-6911f91e48f8.png)

**Comment by BONNe** [comment]
Fixed in 2.3.0
